version: "3"
services:
  node:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    network_mode: host

  db:
    image: mysql:5
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - ./dockerDb/data:/docker-entrypoint-initdb.d/
    network_mode: host


volumes:
  db_volume:

